// Generated by CoffeeScript 1.10.0
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  window.AppView = (function(superClass) {
    extend(AppView, superClass);

    function AppView() {
      return AppView.__super__.constructor.apply(this, arguments);
    }

    AppView.prototype.el = '#app';

    AppView.prototype.initialize = function() {
      this.title = new TitleView();
      this.input = new InputView({
        collection: this.collection
      });
      this.list = new ListView({
        collection: this.collection
      });
      return this.render();
    };

    AppView.prototype.render = function() {
      this.$el.append([this.title.$el, this.input.$el, this.list.$el]);
      return this;
    };

    return AppView;

  })(Backbone.View);

}).call(this);

//# sourceMappingURL=AppView.js.map
