// Generated by CoffeeScript 1.10.0
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  window.ListView = (function(superClass) {
    extend(ListView, superClass);

    function ListView() {
      return ListView.__super__.constructor.apply(this, arguments);
    }

    ListView.prototype.id = 'list';

    ListView.prototype.initialize = function() {
      this.collection.on('add', (function(_this) {
        return function() {
          return _this.render();
        };
      })(this));
      return this.render();
    };

    ListView.prototype.render = function() {
      var $els;
      this.$el.empty();
      console.log("trying to render the list");
      this.entries = this.collection.models.map((function(_this) {
        return function(model) {
          return new EntryView({
            model: model
          });
        };
      })(this));
      $els = this.entries.map(function(entry) {
        return entry.$el;
      });
      this.$el.append($els);
      return this;
    };

    return ListView;

  })(Backbone.View);

}).call(this);

//# sourceMappingURL=ListView.js.map
