// Generated by CoffeeScript 1.10.0
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  window.TitleView = (function(superClass) {
    extend(TitleView, superClass);

    function TitleView() {
      return TitleView.__super__.constructor.apply(this, arguments);
    }

    TitleView.prototype.el = '<h1>';

    TitleView.prototype.initialize = function() {
      return this.render();
    };

    TitleView.prototype.render = function() {
      this.$el.text('How\'s the weather?');
      return this;
    };

    return TitleView;

  })(Backbone.View);

}).call(this);

//# sourceMappingURL=TitleView.js.map
