// Generated by CoffeeScript 1.10.0
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  window.WeatherEntry = (function(superClass) {
    extend(WeatherEntry, superClass);

    function WeatherEntry() {
      return WeatherEntry.__super__.constructor.apply(this, arguments);
    }

    WeatherEntry.prototype.defaults = {
      zipcode: '',
      city: '',
      weather: '',
      unit: '°F'
    };

    WeatherEntry.prototype.initialize = function() {
      return console.log("creating a model");
    };

    WeatherEntry.prototype.toggleUnit = function() {
      var celsius, fahrenheit, isImperial;
      isImperial = this.get('unit') === '°F';
      if (isImperial) {
        celsius = (this.get('weather') - 32) * (5 / 9);
        return this.set({
          'unit': '°C',
          'weather': celsius.toFixed(2)
        });
      } else {
        fahrenheit = (this.get('weather') / (5 / 9)) + 32;
        return this.set({
          'unit': '°F',
          'weather': fahrenheit.toFixed(2)
        });
      }
    };

    return WeatherEntry;

  })(Backbone.Model);

}).call(this);

//# sourceMappingURL=WeatherEntry.js.map
