// Generated by CoffeeScript 1.10.0
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  window.Weather = (function(superClass) {
    extend(Weather, superClass);

    function Weather() {
      return Weather.__super__.constructor.apply(this, arguments);
    }

    Weather.prototype.model = WeatherEntry;

    Weather.prototype.addWeatherEntry = function(zipcode) {
      var that;
      that = this;
      return $.get('http://api.openweathermap.org/data/2.5/weather?zip=' + zipcode + ',us&units=imperial&APPID=5c680e5d8c8f29befb9f1c239dfae90b', function(data) {
        return that.add({
          zipcode: zipcode,
          city: data.name,
          weather: data.main.temp.toFixed(2)
        });
      });
    };

    return Weather;

  })(Backbone.Collection);

}).call(this);

//# sourceMappingURL=Weather.js.map
